controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - steering_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position

forward_velocity_controller:
  ros__parameters:
    joints:
      - rear_axle_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
